---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  require_chef_for_busser: false
  playbook: test/test.yml
  enable_yum_epel: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    driver_config:
      image: wmaramos/kitchen-ubuntu:16.04
      volume: /sys/fs/cgroup:/sys/fs/cgroup
      run_command: /sbin/init
  - name: centos-6
  - name: centos-7
    driver_config:
      image: wmaramos/kitchen-centos:7
      volume: /sys/fs/cgroup:/sys/fs/cgroup
      run_command: /usr/sbin/init
  - name: debian-8
    driver_config:
      image: wmaramos/kitchen-debian:8
      volume: /sys/fs/cgroup:/sys/fs/cgroup
      run_command: /sbin/init
  - name: amazonlinux
    driver_config:
      platform: centos
  - name: opensuse-42
    driver_config:
      image: wmaramos/kitchen-opensuse:42.3
      volume: /sys/fs/cgroup:/sys/fs/cgroup
      run_command: /usr/lib/systemd/systemd --system

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
