---
- name: Install Repository
  yum:
    name: "{{ zabbix_rhel_release_pkg_url }}"
    state: present

- name: Ensure zabbix packages is installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-agent
    - zabbix-sender

- name: Set facts for RedHat/Centos
  set_fact:
    is_systemd={% if ansible_distribution_version is version('7', '>=') %}true{% else %}false{% endif %}
    is_sysv={% if ansible_distribution_version is version('7', '<') %}true{% else %}false{% endif %}
