---
- name: Install Repository
  yum:
    name: "{{ zabbix_amazon_release_pkg_url }}"
    state: present

- name: Ensure zabbix packages is installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - zabbix-agent
    - zabbix-sender

- name: Set facts for Amazon Linux
  set_fact:
    is_systemd: false
    is_sysv: true
