- name: Script for deregister Host from Zabbix
  template:
    src: deregister.py.j2
    dest: "{{ zabbix_conf_dir }}/scripts/deregister.py"

- name: Ensure deregister is setup for Systemd
  template:
    src: deregister.service.j2
    dest: /etc/systemd/system/zabbix-deregister.service
    owner: root
    group: root
  when: is_systemd

- name: Ensure deregister is setup for Sysv
  file:
    src: "{{ zabbix_conf_dir }}/scripts/deregister.py"
    dest: /etc/rc0.d/K14zabbix-deregister
    state: link
  when: is_sysv
